apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: httpd-restart-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: httpd-restart
            image: httpd:latest
            command: ["/bin/sh", "-c", "systemctl restart httpd"]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
