apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
spec:
  containers:
  - name: apache-container
    image: httpd
    volumeMounts:
    - name: common-volume
      mountPath: /usr/local/apache2/htdocs
  - name: busybox-container
    image: busybox
    volumeMounts:
    - name: common-volume
      mountPath: /data
  volumes:
  - name: common-volume
    emptyDir: {}
