apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
  - name: apache
    image: httpd
    livenessProbe:
      exec:
        command:
        - curl
        - http://localhost
      initialDelaySeconds: 30
      periodSeconds: 30
