apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
  - name: apache
    image: httpd
    volumeMounts:
    - name: apache-volume
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: apache-volume
    hostPath:
      path: /data/apache
